/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'name' : IDL.Text,
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const Congestion = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TrafficSegment = IDL.Record({
  'id' : IDL.Text,
  'congestion' : Congestion,
});

export const idlService = IDL.Service({
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getAllTrafficSegments' : IDL.Func([], [IDL.Vec(TrafficSegment)], ['query']),
  'getTrafficSegment' : IDL.Func([IDL.Text], [TrafficSegment], ['query']),
  'initialize' : IDL.Func([], [], []),
  'recordRouteRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'name' : IDL.Text,
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const Congestion = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TrafficSegment = IDL.Record({
    'id' : IDL.Text,
    'congestion' : Congestion,
  });
  
  return IDL.Service({
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getAllTrafficSegments' : IDL.Func(
        [],
        [IDL.Vec(TrafficSegment)],
        ['query'],
      ),
    'getTrafficSegment' : IDL.Func([IDL.Text], [TrafficSegment], ['query']),
    'initialize' : IDL.Func([], [], []),
    'recordRouteRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };